services:
  seek_web:
    build:
      context: ./backend
      dockerfile: docker/produccion/Dockerfile
    restart: always
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - seek_mongo

  nginx:
    image: nginx:alpine
    container_name: seek_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/docker/produccion/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - seek_web

  seek_mongo:
    image: mongo:8
    container_name: seek_mongo
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
