services:
    seek_web:
        build:
            context: ./backend
            dockerfile: docker/Dockerfile
        restart: always
        entrypoint: /docker-entrypoint.sh
        volumes:
            - ./backend/:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - seek_mongo
    seek_mongo:
        image: mongo:8
        container_name: seek_mongo
        env_file:
            - ./.env
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/data/db
    seek_frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: seek_frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "5173:5173"
        working_dir: /app
        command: ["npm", "run", "dev", "--", "--host"]
        env_file:
            - ./.env
volumes:
  mongo_data:
